apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "postfix.fullname" . }}
  labels:
    app: {{ template "postfix.name" . }}
    chart: {{ template "postfix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "postfix.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "postfix.name" . }}
        release: {{ .Release.Name }}
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9154"
        prometheus.io/scrape: "true"
      {{- end }}
    spec:
      serviceAccountName: {{ template "postfix.serviceAccountName" . }}
      containers:
      {{- if .Values.metrics.enabled }}
        - name: metrics
          image: "{{ .Values.metrics.image.repository }}:{{ tpl .Values.metrics.image.tag . }}"
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9154
              protocol: TCP
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: spool
            mountPath: /var/spool/postfix
          resources:
            {{- toYaml .Values.metrics.resources | nindent 12 }}
      {{- end }}
      - name: {{ template "postfix.name" . }}
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TX_SMTP_RELAY_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ template "postfix.fullname" . }}
              key: tx-smtp-relay-host
        - name: TX_SMTP_RELAY_MYHOSTNAME
          valueFrom:
            configMapKeyRef:
              name: {{ template "postfix.fullname" . }}
              key: tx-smtp-relay-myhostname
        - name: TX_SMTP_RELAY_NETWORKS
          valueFrom:
            configMapKeyRef:
              name: {{ template "postfix.fullname" . }}
              key: tx-smtp-relay-networks
        - name: TX_SMTP_RELAY_USERNAME
          valueFrom:
            configMapKeyRef:
              name: {{ template "postfix.fullname" . }}
              key: tx-smtp-relay-username
        - name: TX_SMTP_RELAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "postfix.fullname" . }}
              key: tx-smtp-relay-password
        - name: POSTFIX_CUSTOM_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ template "postfix.fullname" . }}
              key: postfix-custom-config
        ports:
          - name: smtp
            containerPort: 25
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
